### ISSUE TITLE
ui is having issues with bodyParser

### ISSUE THREAD

**Issue by JimBarrows** [JimBarrows/SavageWorldsVirtualTableTop#84]
Sat, 09 Apr 2016 01:17:00 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at server.js:24:10
ui          | Sat, 09 Apr 2016 01:17:00 GMT body-parser deprecated urlencoded: explicitly specify "extended: true" for extended parsing at node_modules/body-parser/index.js:74:29
ui          | Sat, 09 Apr 2016 01:17:00 GMT express-session deprecated undefined resave option; provide resave option at server.js:25:10
ui          | Sat, 09 Apr 2016 01:17:00 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at server.js:25:10

**Comment by JimBarrows** [comment]
Many updates since then.  This error is not longer being seen.
